import type { Metadata } from "next";
import { Poppins, Cedarville_Cursive } from "next/font/google";
import "./globals.css";

import Header from "@/fragments/Header";
import { Footer } from "@/fragments/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="bg-slate-300 scroll-smooth">
      <body>
        <main className={`${poppins.className}`}>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
