import type { Metadata } from "next";
import { Poppins, Cedarville_Cursive } from "next/font/google";
import "./globals.css";

import Header from "@/fragments/Header";
import { Footer } from "@/fragments/Footer";
import SideNavBar from "@/fragments/SideNavBar";
import { LenisScroller } from "@/fragments/SmoothScroller";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR" className="bg-gray-300 ">
      <body>
        <LenisScroller />
        <section className="noise"></section>
        <SideNavBar />
        <main className={`${poppins.className}`}>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
